#!/bin/bash
# rm -fr _packaged/ && _bin/chef_client_remote robi-test queue dps_app dps_app::databag_test

usage="_bin/chef-client-remote <stack name>  <layer name> <cookbook> <recipe>..."

if [ "" == "$CHEF_USER" ]; then
	>&2 echo "Please export var CHEF_USER"
	exit 1
fi
	
OPSWORKS_STACK=$1
if [ "" == "$OPSWORKS_STACK" ]; then
	>&2 echo "Missing stack name as first argument"
	echo $usage
	exit 1
fi
OPSWORKS_LAYER=$2
if [ "" == "$OPSWORKS_LAYER" ]; then
	>&2 echo "Missing layer name as second argument"
	echo $usage
	exit 1
fi

COOKBOOK="dps_app"
if [ "" == "$COOKBOOK" ]; then
	>&2 echo "Missing cookbook name as third argument"
	echo $usage
	exit 1
fi

if [ "" == "$4" ]; then
	>&2 echo "No recipes provided as arguments"
	echo $usage
	exit 1
fi
if [ "" == "$SLEEP" ]; then
	SLEEP=0
fi

recipes="recipe[$4]"
for i in "${@:5}"
do
	recipes="${recipes},recipe[$i]"
done

[ ! -d _packaged/ ] && mkdir _packaged/ || true
if [ ! -d _packaged/$COOKBOOK ]; then
       _bin/package-one $COOKBOOK
fi
currentpwd=$(pwd)
(berks package $currentpwd/_packaged/$COOKBOOK/package.tar.gz && cd $currentpwd/_packaged/$COOKBOOK && tar -zxvf package.tar.gz)
cp -r $COOKBOOK _packaged/$COOKBOOK/cookbooks/
[ -d _packaged/$COOKBOOK/data_bags ] && rm -rf _packaged/$COOKBOOK/data_bags || true

ips=($(_bin/ls-instances "${OPSWORKS_STACK}" $OPSWORKS_LAYER))
for i in "${ips[@]}"
do
	rsync -avr _packaged/$COOKBOOK/ $CHEF_USER@$i:/tmp/opsworks/
	ssh $CHEF_USER@$i "bash -c \"cp -r /var/chef/runs/\$(ls -t /var/chef/runs/ | head -1)/data_bags /tmp/opsworks/\""
	ssh $CHEF_USER@$i "sudo su - root -c 'cd /tmp/opsworks/ && chef-client -z -o ${recipes}'"
	echo "SLEEPING $SLEEP"
	sleep $SLEEP
done
