#!/bin/bash -ex
OPSWORKS_STACK=$1
if [ "" == "$OPSWORKS_STACK" ]; then
	>&2 echo "Missing stack name as first argument"
	exit 1
fi
OPSWORKS_LAYER=$2
if [ "" == "$OPSWORKS_LAYER" ]; then
	>&2 echo "Missing layer name as second argument"
	exit 1
fi
STACK_ID=$(aws opsworks describe-stacks  | jq --raw-output ".Stacks | .[] | select(.Name == \"${OPSWORKS_STACK}\") | .StackId")
if [ "" == "${STACK_ID}" ]; then
	>&2 echo "Could not find stack ${OPSWORKS_STACK}"
	exit 1
fi
LAYER_ID=$(aws opsworks describe-layers --stack-id=$STACK_ID | jq --raw-output ".Layers | .[] | select(.Name == \"${OPSWORKS_LAYER}\") | .LayerId")
if [ "" == "${LAYER_ID}" ]; then
	>&2 echo "Could not find layer ${OPSWORKS_LAYER} on stack ${OPSWORKS_STACK}"
	exit 1
fi
aws opsworks describe-instances --layer-id=${LAYER_ID} | jq --raw-output ".Instances | .[]  | select(.Status == \"online\") | .PrivateIp"

